# Generated by Django 4.1.1 on 2022-09-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_post_join_words_post_join_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='join_value',
            new_name='join_v',
        ),
    ]
