# Generated by Django 4.1.1 on 2022-09-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pkLink',
        ),
    ]
