# Generated by Django 4.1.1 on 2022-09-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_latestlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestlink',
            name='word',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
