# Generated by Django 4.1.1 on 2022-10-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_latestlink_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
